Adding Pythagoras Theorem
TheAlgorithms/JavaScript pull request #1072
Opened 2022-07-30 08:55 UTC by cwh0430

To calculate the hypothenuse, adjacent and base of the triangle

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [✓ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [✓ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [✓ ] This pull request is all my own work -- I have not plagiarized.
- [✓ ] I know that pull requests will not be merged if they fail the automated tests.
- [✓ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [✓ ] All new JavaScript files are placed inside an existing directory.
- [ ✓] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [✓ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [✓ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-07-30 16:34 UTC, raklaptudirm requested changes
Add some tests for the functions.

2022-07-31 18:48 UTC, appgurueu requested changes
Please rename the file to `PythagoreanTheorem`.

`calcAdjacent` and `calcBase` are practically the same function (`a = sqrt(c² - b²)` and `b = sqrt(c² - a²)`) - deduplicate them. Order shouldn't matter for `a` and `b` (adjacent vs. base).

2022-07-31 18:58 UTC, appgurueu requested changes
You've got two tests both for `adjacent` & `base` calculation. Please merge them in a single function.

2022-07-31 20:39 UTC, appgurueu commented on Maths/PythagoreanTheorem.js
> +    const side2 = Math.sqrt((hypothenuse ** 2) - (side1 ** 2))
indentation here is off

2022-08-02 21:37 UTC, cwh0430 reviewed
added test functions

2022-08-03 08:51 UTC, appgurueu approved these changes
Looks good enough (would perhaps rename `calcOtherSides` to `calcOtherSide` since it calculates *one* other side).

2022-08-03 12:59 UTC, appgurueu submitted a review, later dismissed

2022-08-03 16:14 UTC, appgurueu commented on Maths/PythagoreanTheorem.js
> +  calcOtherSides,
You forgot to rename this too.

2022-08-03 19:43 UTC, appgurueu approved these changes

2022-08-03 19:48 UTC, appgurueu requested changes
Please use pythagorean triplets as tests. Your current tests are invalid.

2022-08-03 19:48 UTC, appgurueu commented on Maths/test/PythagoreanTheorem.test.js
> +  const hypothenuse = pytheorem.calcHypothenuse(2.0, 3.0)
4 + 9 = 13; sqrt(13) != 4

2022-08-03 19:48 UTC, appgurueu commented on Maths/test/PythagoreanTheorem.test.js
> +  const side = pytheorem.calcOtherSide(4.0, 3.0)
16 - 9 = 7; sqrt(7) != 2

2022-08-21 20:45 UTC, closed without merging