Invert array
TheAlgorithms/JavaScript pull request #1197
Opened 2022-10-15 20:11 UTC by SczSca

### Describe your change:

- [X] Add an algorithm: Invert Array.
Algorithm to invert elements in an array: 
[a,b,c,d] //output [d,c,b,a]

### Checklist:

- [ X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [X ] This pull request is all my own work -- I have not plagiarized.
- [ X] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [X ] All new JavaScript files are placed inside an existing directory.
- [ X] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-16 04:56 UTC, syedjafer commented on Data-Structures/Array/InvertArray.js
> +
Please user standard js for code style correction. 
Refer: Contributing.md - https://github.com/TheAlgorithms/JavaScript/blob/master/CONTRIBUTING.md#coding-style

For Standard JS - https://standardjs.com/

2022-10-17 06:33 UTC, appgurueu requested changes
Please...
1. Name this `reverse`
2. Use a proper JSDoc comment
3. Why is your comment screaming at me?
4. Don't use a `const Array` in your tests (shadows the built-in `Array`) - just inline the arrays
5. Consider using `each` here
6. Declare `temp` as `const` inside the loop

2022-10-18 03:12 UTC, SczSca commented
> Please...
> 
> 1. Name this `reverse`
> 2. Use a proper JSDoc comment
> 3. Why is your comment screaming at me?
> 4. Don't use a `const Array` in your tests (shadows the built-in `Array`) - just inline the arrays
> 5. Consider using `each` here
> 6. Declare `temp` as `const` inside the loop

Just to be sure:
1. You mean changing name files to 'Reverse.js' and 'Reverse.test.js' ?
2/3. Sorry I am still learning to being consistent
5. For each wouldn't work because it loops over half array

Sorry for these mistakes, I'm a beginner student that heard and is learning about the open-source software

2022-10-18 06:23 UTC, appgurueu commented
>     1. You mean changing name files to 'Reverse.js' and 'Reverse.test.js' ?
>        2/3. Sorry I am still learning to being consistent

Not only the file names, also the function name.

>     2. For each wouldn't work because it loops over half array

Sorry, I should've made myself more clear. I did not mean "use for-each for reversing". I meant use Jest's `each` for testing.

2022-10-18 22:55 UTC, SczSca commented
> > ```
> > 1. You mean changing name files to 'Reverse.js' and 'Reverse.test.js' ?
> >    2/3. Sorry I am still learning to being consistent
> > ```
> 
> Not only the file names, also the function name.
> 
> > ```
> > 2. For each wouldn't work because it loops over half array
> > ```
> 
> Sorry, I should've made myself more clear. I did not mean "use for-each for reversing". I meant use Jest's `each` for testing.

Wanted to sent the commit to my fork to change the name files, but sent it here anyways...

2022-10-19 02:10 UTC, SczSca commented
> > ```
> > 1. You mean changing name files to 'Reverse.js' and 'Reverse.test.js' ?
> >    2/3. Sorry I am still learning to being consistent
> > ```
> 
> Not only the file names, also the function name.
> 
> > ```
> > 2. For each wouldn't work because it loops over half array
> > ```
> 
> Sorry, I should've made myself more clear. I did not mean "use for-each for reversing". I meant use Jest's `each` for testing.

Everything is done, I guess.
Sorry for the inconveniences and the amount of commits made. I'm a beginner student that heard a talk about open-source software in Hacktoberfest and wanted to give it a try with some code that was made in one of my classes

2022-10-19 07:45 UTC, appgurueu reviewed
You forgot to rename the files...

2022-10-19 15:07 UTC, SczSca commented
> You forgot to rename the files...

the renamed file names are not reflected on the last two commits? I see te files renamed, but I might be wrong

![image](https://user-images.githubusercontent.com/90069772/196727572-d5897f9a-c23d-48b1-b3c1-bd5f723a9e20.png)

![image](https://user-images.githubusercontent.com/90069772/196727703-6a807e04-6f67-430b-86ef-7f6791f3ea8f.png)

![image](https://user-images.githubusercontent.com/90069772/196728081-1b7e40c8-3c03-4dbd-ba4e-0265d18baefb.png)

2022-10-19 15:42 UTC, appgurueu approved these changes

2022-10-20 11:38 UTC, raklaptudirm approved these changes

2022-10-20 11:38 UTC, merged