Volume of Torus
TheAlgorithms/JavaScript pull request #1220
Opened 2022-10-21 05:24 UTC by ChrisO345

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:
- Added volume of torus algorithm to Volume.js

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-21 08:44 UTC, appgurueu commented on Maths/Volume.js
> +  return (PI * innerRadius^2) * (2 * PI * outerRadius)
Please consistently use `inner`/`outer` radius (you're calling it `minor`/`major` below)

2022-10-21 11:08 UTC, appgurueu commented on Maths/Volume.js
> +  return (PI ** 2 * 2 * majorRadius * minorRadius ** 2)
now that's just redundant...

2022-10-21 11:12 UTC, ChrisO345 commented on Maths/Volume.js
> +  return (PI ** 2 * 2 * majorRadius * minorRadius ** 2)
In what way?

2022-10-21 13:28 UTC, appgurueu commented on Maths/Volume.js
> +  return (PI ** 2 * 2 * majorRadius * minorRadius ** 2)
It's redundant with the below code

2022-10-22 08:15 UTC, appgurueu requested changes
Please

1. Add at least one test
2. Use a proper JSDoc comment

2023-09-20 20:14 UTC, closed without merging