Added sphere volume
TheAlgorithms/JavaScript pull request #1249
Opened 2022-10-30 05:45 UTC by Lcvieira2001

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [X] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-30 08:31 UTC, appgurueu requested changes
Please combine this with the sphere surface area in a class. Same comments apply here.

2022-10-30 15:15 UTC, appgurueu commented on Geometry/Test/Sphere.test.js
> +test('The Volume of a cone with base radius equal to 3 and height equal to 5', () => {
Sphere, not cone. Same below.

2022-10-30 15:15 UTC, appgurueu commented on Geometry/Sphere.js
> + * https://en.wikipedia.org/wiki/Sphere
@see

2022-10-30 15:24 UTC, appgurueu approved these changes

2022-10-31 16:39 UTC, raklaptudirm approved these changes

2022-10-31 16:39 UTC, merged