add MinMax game theory JS #1193 commented out test case and .at(index) fix for not passing tests
TheAlgorithms/JavaScript pull request #1278
Opened 2023-01-13 07:56 UTC by devhiteshk

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x ] Add an algorithm?
- [x ] Fix a bug or typo in an existing algorithm?
- [ x] Documentation change?

### Checklist:

- [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x ] This pull request is all my own work -- I have not plagiarized.
- [x ] I know that pull requests will not be merged if they fail the automated tests.
- [ x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new JavaScript files are placed inside an existing directory.
- [ x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-01-13 07:58 UTC, devhiteshk commented
Dear Maintainers please have a look when you get active :)

2023-01-13 08:05 UTC, appgurueu commented on Maths/Fibonacci.js
> +        list.push(list[list.length - 1] + list[list.length - 2])
Undo this unrelated change.

2023-01-13 08:06 UTC, appgurueu requested changes
You have various unrelated changes in there, including bumping some dependencies.

2023-01-13 09:12 UTC, devhiteshk commented
I think now it is fine

2023-01-14 18:01 UTC, devhiteshk commented
> You have various unrelated changes in there, including bumping some dependencies.

All conflicts have now been resolved

2023-01-14 18:54 UTC, appgurueu requested changes
Consider refactoring out the class. In this example, a simple function should suffice. If you don't want to repeat some calculations, consider a simple function containing a recursive closure:

```javascript
export default function solveMinMax(scores, ...) {
    const height = Math.log2(scores.length)
    const solve = (...) => {
        ...
        ...(solve(...), solve(...))
        ...
    }
    return solve(...)
}
```

Furthermore, what exactly is the merit of this? In its current form, this:

* Needs to have all scores evaluated beforehand anyways, because they must be provided in an array;
* Always recurses into both branches.

MinMax is a tree search pruning technique. Two questions:

* Where is the pruning - which nodes are we pruning?
* How is lazily evaluating scores implemented? I'd suggest passing a function to get a score for a node rather than an array which needs to be fully evaluated.

2023-01-14 18:54 UTC, appgurueu commented on Project-Euler/test/Problem044.test.js
> +  // test('if the number is greater or equal to 2167', () => {
This unrelated change still doesn't belong here.

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/tests/MinMax.test.js
> +  it('should return 65 for MinMax([90, 23, 6, 33, 21, 65, 123, 34423],0,0,true)', () => {
This test is practically equivalent to the below test. You're also duplicating the contents in the description. Please see the [TypeScript guide for writing good tests](https://github.com/TheAlgorithms/TypeScript/blob/master/CONTRIBUTING.md#writing-good-tests).

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/MinMax.js
> +// MinMax(scores, depth, nodeindex, ismax)
This outcommented code ought to be removed.

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/MinMax.js
> +class MinMax {
Why not prefix this with `export` (perhaps even `export default`) rather than `export`ing below?

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/MinMax.js
> +  constructor (scores, depth, nodeIndex, isMax) {
This constructor is completely superfluous - you're passing all these as arguments to `solve` later on. I'm questioning whether this should be a class at all - IMO it should just be a single `solve` function that checks it parameters and recurses.

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/MinMax.js
> +  get_ans () {
Not in `lowerCamelCase`

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/MinMax.js
> +    this.answer = this.solve(
Storing the answer in the class is dirty IMO; why not just `return` it?

2023-01-14 18:54 UTC, appgurueu commented on Backtracking/MinMax.js
> +  solve (depth, nodeIndex, isMax, scores, height) {
You don't have to pass all of these as parameters - you already have them as instance variables.

2023-01-14 18:59 UTC, appgurueu commented on Backtracking/MinMax.js
> +//     nodeIndex is index of current node in scores[].
This comment is messy. There are no Python-like doc comments in this repo.

2023-01-14 19:00 UTC, appgurueu commented on Backtracking/MinMax.js
> + *  Min Max problem
Please make this a proper JSDoc comment.

2023-01-15 04:23 UTC, devhiteshk commented
I think I can't code :(

2023-01-15 04:23 UTC, closed without merging

2023-01-15 10:31 UTC, appgurueu commented
Don't worry, your code seems to be a correct port of the code found on Geeks for Geeks. It's just that the Geeks for Geeks code is poorly structured (IMO).