feat : Program to find Kth Symbol of Grammar
TheAlgorithms/JavaScript pull request #1326
Opened 2023-05-25 14:06 UTC by hecker1002

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-05-25 14:45 UTC, appgurueu requested changes
Missing proper tests, CI is failing.

2023-05-25 14:45 UTC, appgurueu commented on Recursive/TowerOfHanoi.js
> +const n = 4
Unrelated change.

2023-05-25 14:45 UTC, appgurueu commented on Recursive/KSymbolOfGrammar.js
> +  let ans = KSymbol( 4, 1)
This should be in a test I assume.

2023-05-25 14:45 UTC, appgurueu commented on Recursive/KSymbolOfGrammar.js
> +function KSymbol(n ,k){
needs more comments, also doesn't abide by our style guidelines

2023-05-25 14:45 UTC, appgurueu commented on Recursive/KSymbolOfGrammar.js
> +// Recursive call function  to find l=k th Symbol of Grammar  (0 => 0,1 , 1=> 1,0)
Please rephrase this

2023-05-30 07:05 UTC, Mohammed-Faizzzz commented
Hi, may I check if help is still required? Please let me know, I would be very much willing to help!

2023-05-30 08:34 UTC, appgurueu commented
> Hi, may I check if help is still required? Please let me know, I would be very much willing to help!

Well, the issues still haven't been resolved.

2024-01-27 15:04 UTC, closed without merging