added fibonacci using formula along with test cases
TheAlgorithms/JavaScript pull request #1358
Opened 2023-09-11 10:28 UTC by dev-madhurendra

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

I added a code which calculates the nth fibonacci number using formula in a very less time.

- [ ✅ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [ ✅ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ ✅ ] This pull request is all my own work -- I have not plagiarized.
- [ ✅ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ✅ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ✅ ] All new JavaScript files are placed inside an existing directory.
- [ ✅ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ✅ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ✅ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-09-11 11:51 UTC, appgurueu requested changes
Please add this to the existing [`Fibonacci.js`](https://github.com/TheAlgorithms/JavaScript/blob/master/Maths/Fibonacci.js) file (and add the tests to the corresponding test file). Use a proper JSDoc comment. Also, use `each` for the test cases.

The formula doesn't need to be a comment, that's redundant with the implementation (also, the formula in the comment seems to differ from the one you implemented?). You can use `x**y` instead of `Math.pow(x, y)`. Note also that Wikipedia suggests a slightly simpler formula for computation by rounding.

Side note: I find calling this O(1) time/space complexity slightly misleading; this is only (trivially) given because the numbers involved have constant size. If this were to use bigints / bigdecimals, it wouldn't be constant time anymore.

2023-09-11 12:29 UTC, appgurueu commented on Maths/test/Fibonacci.test.js
> +  it('should calculate the correct Fibonacci number for n = 0', () => {
As said, please use Jest's `each` for these.

2023-09-11 12:30 UTC, appgurueu commented on Maths/Fibonacci.js
> +  const sqrt5 = Math.sqrt(5)
I'd hoist these three variables out of the function.

2023-09-11 12:30 UTC, appgurueu commented on Maths/Fibonacci.js
> +  const result = (phi ** n - psi ** n) / sqrt5
This variable can be inlined.

2023-09-11 12:56 UTC, appgurueu submitted a review, later dismissed

2023-09-12 05:47 UTC, dev-madhurendra commented
@appgurueu When I'll be able to merge this PR ?

2023-09-12 09:41 UTC, appgurueu commented
> @appgurueu When I'll be able to merge this PR ?

It's still waiting on a second review from @raklaptudirm.

2023-09-19 11:09 UTC, raklaptudirm requested changes
Sorry for the late review, but consider adding a resource to the formula used here.

2023-09-19 14:59 UTC, raklaptudirm approved these changes

2023-09-19 14:59 UTC, merged