added algo for checking the number is power of four or not
TheAlgorithms/JavaScript pull request #1360
Opened 2023-09-11 15:09 UTC by dev-madhurendra

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-09-11 17:57 UTC, appgurueu commented on Bit-Manipulation/IsPowerofFour.js
> +    A number will be power of four if and only if there is a 1 in the binary
This is wrong. `10` (2) is not a power of 4. A number is a power of four if there is a single set bit followed by an even number of zeroes. What really makes this work is the `n % 3 === 1`, which rules out powers of 2 which are not powers of 4.

2023-09-11 17:58 UTC, appgurueu requested changes
Again, please use a proper JSDoc comment; I'd also remove most of the explanation, esp. those items which are fully redundant with the code ("[a]nd the and of n&n-1 will be 0" f.e.).

2023-09-12 10:42 UTC, appgurueu reviewed
Again, please use proper [JSDoc](https://jsdoc.app/) comments.

2023-09-21 14:42 UTC, appgurueu approved these changes

2023-09-22 09:21 UTC, raklaptudirm approved these changes

2023-09-22 09:21 UTC, merged