Add Length Conversion
TheAlgorithms/JavaScript pull request #1390
Opened 2023-10-01 13:42 UTC by 0APOCALYPSE0

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

I have added Algorithms for Length Conversion.

### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-10-01 14:05 UTC, appgurueu requested changes
I don't think this is interesting enough algorithmically yet; the code also suffers from unnecessary code duplication: You've effectively hardcoded the cartesian product of {mile, kilometer, meter, centimeter, feet, yard, inch} with itself (and excepting self-to-self, of course).

I think you should change your function to be something like `function LengthConversion(length, fromUnit, toUnit)` where `fromUnit` and `toUnit` are standard abbreviations like `km` for kilometre or similar. Then you should use a lookup dict which maps these to meters. The calculation then becomes `length * meters[fromUnit] / meters[toUnit]`, and you get away with a fraction of the code.

2023-10-01 15:05 UTC, 0APOCALYPSE0 commented
@appgurueu  I have updated. Could you please review it now?
Thanks

2023-10-01 15:21 UTC, appgurueu reviewed
Great, now please

2023-10-01 15:21 UTC, appgurueu commented on Conversions/LengthConversion.js
> +    return 'Invalid units'
You should throw an error.

2023-10-01 15:21 UTC, appgurueu commented on Conversions/LengthConversion.js
> +// // This files has functions to convert different length units
Please use a proper JSDoc comment.

2023-10-01 16:05 UTC, appgurueu approved these changes

2023-10-02 07:05 UTC, raklaptudirm approved these changes

2023-10-02 07:05 UTC, merged