feat: added Gray Code algorithm
TheAlgorithms/JavaScript pull request #1425
Opened 2023-10-04 06:08 UTC by Harshdev098

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [Yes] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [Yes ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [Yes ] This pull request is all my own work -- I have not plagiarized.
- [Yes ] I know that pull requests will not be merged if they fail the automated tests.
- [Yes ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ Yes] All new JavaScript files are placed inside an existing directory.
- [Yes ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-10-04 12:23 UTC, appgurueu requested changes
* Use a JSDoc comment for the exported function
* Inline the variables in your test, use binary number literals (`0b...`) to make the tests more understandable. Also, test more cases than just n=3 (for example the edge case n=0 is currently untested); you may want to use `each` for this.

2023-10-04 23:16 UTC, appgurueu submitted a review, later dismissed

2023-10-05 10:09 UTC, raklaptudirm requested changes
Add some comments explaining the algorithm and adding some resources for further reading.

2023-10-06 10:15 UTC, raklaptudirm approved these changes

2023-10-08 13:24 UTC, appgurueu approved these changes

2023-10-08 13:25 UTC, merged