Update AllCombinationsOfSizeK.js
TheAlgorithms/JavaScript pull request #1530
Opened 2023-10-14 07:42 UTC by imrahulkb

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

This PR modifies a current algorithm for  **AllCombinationsOfSizeK**. Four parameters made up the original **findCombinations()** method, and they were duplicated for each stack call. Since the modifications are kept in the instance variables, the modified **findCombinations()** method does not require any parameters. In this case, there will be **far fewer** local variables that need to be initialized overall on each recursive call.
There was also a for loop in the original technique. The updates function is **entirely recursive** and lacks a for loop.

### Checklist:

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-10-17 17:43 UTC, appgurueu requested changes
Looks good, however formatting seems broken. If you're already refactoring this, could you get rid of the class entirely? This should be a single function taking `n` and `k` as parameters instead. Ideally the API should also be a generator rather than producing a list.

2023-10-23 17:08 UTC, appgurueu approved these changes

2023-10-23 17:08 UTC, appgurueu requested changes
You'll need to fix the tests, though. They currently still expect a class.

2023-10-29 13:23 UTC, imrahulkb commented
I am not able to get that why there is code style error in this pull request

2023-10-29 22:03 UTC, appgurueu approved these changes

2023-10-30 05:39 UTC, raklaptudirm approved these changes

2023-10-30 05:40 UTC, merged