Update Problem001.js
TheAlgorithms/JavaScript pull request #1536
Opened 2023-10-14 14:02 UTC by imrahulkb

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:
**Eliminated the for loop** and thus converted the time complexity **O(N) to O(1)** 

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-10-15 18:20 UTC, appgurueu commented on Project-Euler/Problem001.js
> +    const nSum = (num,frequency)=>{
Just `(num, frequency) => frequency*(frequency+1)*num>>1`. Probably should also get a comment to explain what is going on here (summation formula for the arithmetic progression).

2023-10-15 18:21 UTC, appgurueu requested changes
Please fix the formatting. Your comments on `nSum` should be at the appropriate place (right next to the definition of `nSum`).

2023-10-29 16:59 UTC, imrahulkb commented
I have made the necessary changes in the formatting and added comment right above the function nSum

2023-10-29 22:01 UTC, appgurueu approved these changes

2023-10-30 05:39 UTC, raklaptudirm approved these changes

2023-10-30 05:39 UTC, merged