Abbreviation
TheAlgorithms/JavaScript pull request #1547
Opened 2023-10-15 17:59 UTC by pertrai1

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-10-29 16:22 UTC, appgurueu commented on Dynamic-Programming/Abbreviation.js
> +  let dp = Array.from({length: n + 1}, () => Array(m + 1).fill(false))
Please give this a more descriptive name such as `canAbbreviate`.

2023-10-29 16:27 UTC, appgurueu requested changes
Mostly there, just some minor things to address.

2023-10-29 16:27 UTC, appgurueu commented on Dynamic-Programming/Abbreviation.js
> + * ### Algorithm
Please add these explanatory comments inside the implementation, at the appropriate places.

2023-10-29 16:27 UTC, appgurueu commented on Dynamic-Programming/Abbreviation.js
> +        if (j < m && a[i].toUpperCase() === b[j]) {
You should explain the rule you employ here.

2023-10-29 16:27 UTC, appgurueu commented on Dynamic-Programming/Abbreviation.js
> +        if (a[i] === a[i].toLowerCase()) {
Same here. Please add a comment.

2023-10-29 16:27 UTC, appgurueu commented on Dynamic-Programming/tests/Abbreviation.test.js
> +  test('it can abbreviate string a to b', () => {
I'd partition the test cases into positives and negatives (two different `test` blocks), then run the individual tests using a helper function `const expectPositive = (word, abbr) => expect(abbreviation(word, abbr)).toBe(true)` to make it somewhat less verbose (matter of taste though).

2023-10-29 16:27 UTC, appgurueu commented on Dynamic-Programming/Abbreviation.js
> +export const abbreviation = (a, b) => {
I'd probably call this `isAbbrevation`. Also, please give `a` and `b` more descriptive names like `word` and `abbr`.

2023-11-13 17:43 UTC, pertrai1 commented
@appgurueu - can you please take a look at the changes made based on the code review? Thanks

2023-11-13 18:42 UTC, appgurueu approved these changes

2023-11-15 13:54 UTC, raklaptudirm approved these changes

2023-11-15 13:55 UTC, merged