Implemented M Coloring Problem
TheAlgorithms/JavaScript pull request #1562
Opened 2023-10-22 07:56 UTC by vedas-dixit

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-10-22 16:11 UTC, appgurueu requested changes
It also seems to me that an adjacency list representation would be more suitable?

2023-10-22 16:11 UTC, appgurueu commented on Backtracking/MColoringProblem.js
> +/*
Use a proper doc comment instead of this.

2023-10-22 16:11 UTC, appgurueu commented on Backtracking/MColoringProblem.js
> +  What is the M Coloring Problem?
This is redundant with the description you have just given.

2023-10-22 16:11 UTC, appgurueu commented on Backtracking/MColoringProblem.js
> +  Solution:
These should be comments on the implementation, on the relevant parts.

2023-10-22 16:11 UTC, appgurueu commented on Backtracking/MColoringProblem.js
> +class MColoring {
There is no need for a class here. This should effectively be a single `function` with parameters `graph` and `m` which returns the colors, or `null` / `undefined` if there is no valid m-coloring. Note that using a function does not prevent you from using and defining "helper functions" *inside the function*.

2023-10-22 16:22 UTC, vedas-dixit commented
Thank you @appgurueu for the detailed review. I appreciate the feedback and suggestions. I'll work on implementing the changes you recommended:

I'll consider switching to an adjacency list representation for better efficiency.
I'll refine the comments, utilize proper JS Doc comments, and ensure that explanations are placed next to the relevant code.
I'll revisit the class-based approach and try to refactor it to a functional one as you suggested.
I'll push these changes soon. Thanks again for the insights!

2023-10-23 16:39 UTC, appgurueu approved these changes

2023-10-24 06:48 UTC, raklaptudirm approved these changes

2023-10-24 06:48 UTC, merged