Added JSDoc documentation to some sorting functions and added TimoSort
TheAlgorithms/Javascript pull request #406
Opened 2020-10-04 15:36 UTC by DarkWarrior703

# Welcome to JavaScript community

### **Describe your change:**

* [x] Add an algorithm?
* [x] Documentation change?
Added Timo Sort.
Added JSDoc documentation to some sorting algorithms.

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #404 `.

2020-10-04 17:26 UTC, itsvinayak requested changes
there are too many changes, please make one file change per commit, read contribution guidelines.
thanks 
@itsvinayak

2020-10-04 17:26 UTC, itsvinayak commented on DIRECTORY.md
> +  * [TimoSort](https://github.com/TheAlgorithms/Javascript/blob/master/Sorts/TimoSort.js)
remove this line it is auto-generated by script

2020-10-04 19:52 UTC, DarkWarrior703 commented
Now it's just TimSort algorithm. I changed it. Tommorow I will make a pull request to add JSDoc to all sorting functions.

2020-10-05 16:44 UTC, itsvinayak approved these changes

2020-10-05 16:45 UTC, merged