Create super
TheAlgorithms/Javascript pull request #541
Opened 2020-10-31 09:33 UTC by sachinpasi

# Welcome to JavaScript community

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new JavaScript files are placed inside an existing directory.
* [ ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-31 10:01 UTC, Khez requested changes

2020-10-31 10:01 UTC, Khez commented on super
> +    }
This doesn't make much sense...

2020-10-31 10:01 UTC, Khez commented on super
> +class rectangle {
Why is `rectangle` lowercase while `Square` is capitalised ?

2020-10-31 10:01 UTC, Khez commented on super
> +}
It would be helpful to have an example usage for people who want to understand how this works.

2020-11-05 09:23 UTC, ruppysuppy reviewed
Go through the [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md) before adding any Pull Request

2021-01-17 04:01 UTC, ruppysuppy commented
Irrelevant PR

2021-01-17 04:01 UTC, closed without merging