add algorithm Breadth-first search
TheAlgorithms/Javascript pull request #571
Opened 2021-02-25 09:53 UTC by algobytewise

# Welcome to JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-02-27 03:22 UTC, ruppysuppy requested changes

2021-02-27 03:22 UTC, ruppysuppy commented on Graphs/BreadthFirstSearch.js
> +  const visited = []
[optimization] use set for keeping track of the visited nodes

2021-02-27 04:25 UTC, algobytewise commented
Thanks for the reminder on sets, I've implemented the changes

2021-02-28 03:11 UTC, ruppysuppy approved these changes

2021-02-28 03:11 UTC, merged