Fix Maths/IsDivisible
TheAlgorithms/Javascript pull request #597
Opened 2021-05-05 05:26 UTC by Masa-Shin

# Welcome to JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-05-13 06:49 UTC, raklaptudirm requested changes

2021-05-13 06:49 UTC, raklaptudirm commented on Maths/IsDivisible.js
> +    throw new Error('All parameters have to be numbers')
As an enhancement, I would suggest throwing a [`TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError).
```js
throw new TypeError("Expected a number")
```

2021-05-21 05:04 UTC, raklaptudirm commented
@Masa-Shin I am pinging because it seems you have abandoned this PR.

2021-05-21 05:08 UTC, Masa-Shin commented
@raklaptudirm 
I will fix it on this weekend thanks.

2021-05-23 08:45 UTC, Masa-Shin commented on Maths/IsDivisible.js
> +    throw new Error('All parameters have to be numbers')
@raklaptudirm 
Fixed!

2021-05-23 08:46 UTC, raklaptudirm approved these changes

2021-05-23 08:48 UTC, raklaptudirm commented
Please fix the standard style issues

2021-05-23 08:51 UTC, raklaptudirm commented
@Masa-Shin please fix the standard style issues.

2021-05-23 09:13 UTC, Masa-Shin commented
@raklaptudirm 
sorry I fixed.

2021-05-23 09:14 UTC, raklaptudirm commented
@Masa-Shin please fix the standard style issues

2021-05-23 09:16 UTC, merged