Refactor Made by João Vitor Balzer
TheAlgorithms/Javascript pull request #653
Opened 2021-08-14 15:32 UTC by joaobalzer

Refactor Made by João Vitor Balzer to the discipline of "ASPECTOS ÁGEIS DE PROGRAMAÇÃO"

2021-08-15 10:20 UTC, raklaptudirm requested changes

2021-08-15 10:20 UTC, raklaptudirm commented on Geometry/ConvexHullGraham.js
> +        upperLenght = upperPoints.length
```suggestion
        upperLength = upperPoints.length
```

2021-08-15 10:20 UTC, raklaptudirm commented on Geometry/ConvexHullGraham.js
> +      let upperLenght = upperPoints.length
```suggestion
      let upperLength = upperPoints.length
```

2021-08-15 10:20 UTC, raklaptudirm commented on Geometry/ConvexHullGraham.js
> +        upperLenght >= 2 &&
```suggestion
        upperLength >= 2 &&
```

2021-08-20 08:00 UTC, raklaptudirm commented
@joaobalzer Please rectify the changes requested.

2021-09-11 20:52 UTC, Bhavyajain21 commented
I would like to work on this issue. What's the next step I can do to  interact with you?

2021-09-12 07:32 UTC, raklaptudirm commented
@Bhavyajain21 Which issue can you specify?

2021-09-18 14:52 UTC, closed without merging