Added the Other algorithm category and an algorithm of find DateToDay method
TheAlgorithms/Javascript pull request #663
Opened 2021-08-22 08:57 UTC by suryapratapsinghsuryavanshi

# Welcome to JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-08-22 10:00 UTC, raklaptudirm requested changes
This PR does not teach anything new. I should suggest trying to implement the day getting by hand, which will we more interesting than using an in-built class.
If you do change that, I believe this file is better suited in the `/Conversions/` catagory.

2021-08-22 11:01 UTC, suryapratapsinghsuryavanshi commented
Sorry, but I don't get your point "I should suggest trying to implement the day getting by hand" can you more elaborate on this point, I think this is more exciting for me to implement something new.

2021-08-22 16:16 UTC, raklaptudirm commented
@sukhpreetsekhon I meant that I do not like the way you have used the `Date` class to get the day. That detail means your algorithm provides no new knowledge tactic for problem solving, and we of course do not want that. I want you to create a function to find the day which will not exploit native behavior. Like for finding the day, you could calculate the number of days passed from a known date, and calculate the day using that.

2021-08-22 19:17 UTC, suryapratapsinghsuryavanshi commented
Thanks, I have already built such a method in my open-source npm package ([SolverJs](https://github.com/suryapratapsinghsuryavanshi/solverjs)). Can you like to see it and make some suggestions? and my name is @suryapratapsinghsuryavanshi. 😄

2021-08-23 03:57 UTC, raklaptudirm commented
@suryapratapsinghsuryavanshi I think you did not understand what I meant. I said the idea of finding the day was good, but implementing it using the `Date` Class is sort of cheating, and people who see that algorithm do not learn anything new. I wanted you to implement finding the day yourself, and not using the `Date` class.

2021-08-23 07:17 UTC, suryapratapsinghsuryavanshi commented
Sorry, I guess this time I've implemented what you wanted.

2021-08-23 07:35 UTC, raklaptudirm approved these changes

2021-08-23 07:35 UTC, merged