merge: optimize the countVowels algo
TheAlgorithms/Javascript pull request #886
Opened 2022-02-16 13:51 UTC by fahimfaisaal

# Welcome to JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

* [x] simplify the algo by using regex and String.prototype.match method
* [x] modified the JS Doc

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.

2022-02-16 13:54 UTC, raklaptudirm requested changes

2022-02-16 13:54 UTC, raklaptudirm commented on String/CountVowels.js
> + * @return {Number} - The number of vowel
```suggestion
 * @return {Number} - The number of vowels
```

2022-02-16 13:54 UTC, raklaptudirm commented on String/CountVowels.js
> +    throw new TypeError('Input should be a string');
```suggestion
    throw new TypeError('Input should be a string')
```

2022-02-16 13:54 UTC, raklaptudirm commented on String/CountVowels.js
> +export { countVowels };
```suggestion
export { countVowels }
```

2022-02-17 07:11 UTC, fahimfaisaal commented
Mistakenly I have pushed the last two commits, that's why I revert that. I'll add again this in the next pull request.

2022-02-17 08:33 UTC, raklaptudirm requested changes
Format your code with `standard.js`.

2022-02-17 11:26 UTC, fahimfaisaal commented
Done ✅

2022-02-17 11:59 UTC, raklaptudirm approved these changes

2022-02-17 12:00 UTC, merged