Upgrade max char
TheAlgorithms/Javascript pull request #983
Opened 2022-04-15 17:55 UTC by fahimfaisaal

# Welcome to the JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Replace the recent algorithm.
- [x] Replace the test case.
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-04-15 19:22 UTC, appgurueu requested changes
To be fair I only see a minor, questionable improvement (the customizable character filter) and a bunch of extraneous syntactic sugar.

2022-04-15 19:22 UTC, appgurueu commented on String/MaxCharacter.js
> +  let max = { char: '', occur: -Infinity }
Why store both? I'd much prefer this being replaced with a `reduce` BTW

2022-04-30 19:17 UTC, fahimfaisaal commented
I feel now it's prefect

2022-05-01 08:51 UTC, appgurueu requested changes
Please fix the raised issues

2022-05-01 18:22 UTC, appgurueu approved these changes

2022-05-02 09:20 UTC, raklaptudirm approved these changes

2022-05-02 09:21 UTC, merged