Update LRUCache.js
TheAlgorithms/Javascript pull request #984
Opened 2022-04-18 16:16 UTC by awojobigodfrey

Added a clear function for cache

# Welcome to the JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-04-18 17:38 UTC, appgurueu commented on Cache/LRUCache.js
> +      return this
Why?

2022-04-18 17:39 UTC, appgurueu requested changes
Please - at the very least - fix your indentation. Why is this feature necessary? Why can't I just call `obj.cache.clear()`?

2022-04-19 05:28 UTC, raklaptudirm commented
`obj.clear()` is less clear then `obj.cache.clear()` imo.

2022-04-19 18:04 UTC, CarlosZoft commented on Cache/LRUCache.js
> +    return this
Why returns "this"?

2022-04-20 04:52 UTC, raklaptudirm commented
@appgurueu should I close this? We both seem to think it is unnecessary and less readable.

2022-04-20 09:07 UTC, closed without merging