feat: added alternative binary search
TheAlgorithms/Javascript pull request #987
Opened 2022-04-19 19:29 UTC by CarlosZoft

# Welcome to the JavaScript community

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Add an algorithm?
- [x] Add some test?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not

2022-04-19 23:57 UTC, appgurueu reviewed
How does this compare to the current implementation? From what I can see it's merely a less readable iterative version. If it showed better traits than the current one, you may replace it. But I don't see the merit of two largely similar iterative implementations.

2022-04-20 04:50 UTC, raklaptudirm commented
@appgurueu since it is being added as a separate implementation, I think we could add it. It is using some more js features, which could be wanted. What do you think?

2022-04-20 09:12 UTC, appgurueu commented on Search/BinarySearch.js
> +    // arr[half] === x => low = half else high = half
Superfluous comment that just explains what a ternary does.

2022-04-20 09:21 UTC, appgurueu requested changes
This PR may indeed be using more JS features (primarily ternaries) but in a wrong manner; they only make the code less readable (except probably for the last ternary). Currently I see only two very tiny advantages over the other impl., the simplification of the term for `mid` and moving the check if found out of the loop; I don't see much of a benefit from the exclusive low & high indices, which is a mere convention. On the other hand however there is rather unreadable code, bad comments and syntactic sugar where it doesn't belong.

The tiny improvements should just be changes to the current implementation.

2022-04-20 09:21 UTC, appgurueu commented on Search/BinarySearch.js
> +    arr[half] < x ? (low = half) : (high = half)
Should rather be written as `if (arr[half] < x) low = half else high = half`.

2022-04-20 09:21 UTC, appgurueu commented on Search/BinarySearch.js
> +  // if arr[high] === x => return high else return -1
Again unneeded comment. Please don't explain what the code does, but *why* it does it (something like: "return -1 if the element doesn't match the searched element").

2022-04-20 09:21 UTC, appgurueu commented on Search/BinarySearch.js
> +// console.log("------------------------------------------")
This code smells like improper testing.

2022-04-20 09:21 UTC, appgurueu commented on Search/BinarySearch.js
> +    const half = Math.floor((low + high) / 2)
This is a minor simplification over what the other implementation does. Consider opening a separate PR, changing the other implementation to `const mid = Math.floor((low + high) / 2)`.

2022-04-20 09:21 UTC, appgurueu commented on Search/BinarySearch.js
> +  let low = -1
Consider adding a comment stating that these bounds are both exclusive (which is probably less intuitive than the other impl.).

2022-04-20 15:58 UTC, raklaptudirm requested changes

2022-04-20 15:58 UTC, raklaptudirm commented on Search/BinarySearch.js
>  /* ---------------------------------- Test ---------------------------------- */
Remove these comments and replace them with proper jest tests.

2022-04-20 15:59 UTC, appgurueu commented
At this point it's similar enough that you should just tidy up the existing implementation (adding proper jest tests) instead.

2022-04-20 19:44 UTC, CarlosZoft commented
I did this

2022-04-20 19:47 UTC, appgurueu requested changes
From a quick glance the tests look fine to me. Definitely a significant improvement. But please deduplicate the code; you can do something like `funcs = {iterative: binarySearchIterative, recursive: binarySearchRecursive}; for (let name in funcs) runTests(name, funcs[name])` where `runTests` is a parameterized function that runs the tests (which are the same for both implementations).

2022-04-20 19:50 UTC, CarlosZoft commented
Nice vision, i will make this!

2022-04-20 20:02 UTC, CarlosZoft commented
lgtm now , what you think?

2022-04-20 20:03 UTC, appgurueu approved these changes
Thank you for your contribution. LGTM!

2022-04-21 06:07 UTC, raklaptudirm approved these changes

2022-04-21 06:07 UTC, merged